### ISSUE TITLE
Release 0.1 Checklist

### ISSUE THREAD

**Issue by cbcunc** [cznethub/dsp#13]
- [x] Code to release merged into develop for all deploy-able repos
   - [x] dsp
   - [x] dspfront
   - [x] dspback 
- [x] Develop deployed to alpha
- [x] Developer tests pass on alpha
   - [x] Automated tests pass
   - [x] Manual tests pass
      - [x] Login with ORCID
      - [x] Navigate to Submit to HydroShare
         - [x] Authorize HydroShare
         - [x] Add files/folders
         - [x] Fill out metadata
         - [x] Save
   - [x] Verify Submission Entry exists for new record
      - [x] Verify in repository
      - [x]  Confirm “View in Repository” links to the HydroShare resource
      - [x] Confirm “Edit” retrieves the correct metadata
      - [x] Update the title in HydroShare then click “Update Record”.  Confirm the title is updated on the submission page
      - [x] Click Delete and confirm the resource is no longer available as a submission and on HydroShare
   - [x] Navigate to Submit to Zenodo
      - [x] Authorize Zenodo
      - [x] Add files
      - [x] Fill out metadata
      - [x] Save
      - [x] Verify Submission Entry exists for new record
         - [x] Verify in repository 
         - [x] Confirm “View in Repository” links to the Zenodo record
         - [x] Confirm “Edit” retrieves the correct metadata
         - [x] Update the title in Zenodo then click “Update Record”.  Confirm the title is updated on the submission page
         - [x] Click Delete and confirm the resource is no longer available as a submission and on Zenodo
 - [x] RC branches created and deployed to beta
- [x] Functional tests pass on beta
- [x] RCs tagged as release and deployed to target
- [x] Acceptance tests pass
- [x] Merge the release tag to master
- [x] Merge master to develop
- [x] Profit

**Comment by cbcunc** [comment]
v0.5.5 deployed to dsp-demo.
