### ISSUE TITLE
Release 1.0 Checklist

### ISSUE THREAD

**Issue by cbcunc** [cznethub/dsp#60]
- [x] Code to release merged into develop for all deploy-able repos
   - [x] dsp
   - [x] dspfront
   - [x] dspback 
- [x] Develop deployed to alpha
- [x] Developer tests pass on alpha
- [x] RC branches created and deployed to beta
- [x] Functional tests pass on beta
- [x] RCs tagged as release and deployed to target
- [x] Acceptance tests pass
- [x] Merge the release tag to master
- [x] Merge master to develop
- [x] Profit
