### ISSUE TITLE
Release 1.1 Checklist

### ISSUE THREAD

**Issue by cbcunc** [cznethub/dsp#84]
- [x] Code to release merged into develop for all deploy-able repos
   - [x] dsp
   - [x] dspfront
   - [x] dspback
- [x] Develop deployed to alpha
- [x] Developer (Unit) tests pass on alpha
- [x] Functional (Selennium on-demand) tests pass on alpha
- [x] RC branches created and deployed to beta
- [x] Functional (Selennium on-demand) tests pass on beta
- [x] Acceptance (manual System) tests pass
- [x] RCs tagged as release
- [x]  Release deployed to production
- [x] Merge the release tag to master
- [x] Merge master to develop
- [x] Profit
